---
- hosts: webservers
  become: yes
  tasks:
  - name: display hostname
    command: hostname -f
    register: myresult
  - name: display result of above tasks
    debug:
      msg: "{{myresult}}"
  - name: install git
    apt:
      name: git
      state: present
  - name: apt clean cache
    apt:
      update_cache: yes   
    when: myresult.stderr==""

  - name: install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr!=""
