---
# tasks file for apacherole
- name: install tomcat
  apt:
    name: tomcat7
    state: present
- name: copy mytom config    
  template:
      src: tempconfig.j2 
      dest: /etc/default/tomcat7
  notify: restart tomcat

- name: install admin packages
  apt:
    name: "{{item}}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples  

- name: copy tomcat interfaces    
  template:
      src: tempconfigusers.j2
      dest: /etc/tomcat7/tomcat-users.xml
  notify: restart tomcat
     
